#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00

PUTDIR=/usr2/postdoc/alizom/work/models/Pseudomonas_fluorescens/kbase
cd $PUTDIR

#source activate /projectnb/bioinfor/SEGRE/alizom

#$  -V
#
python -c "import time;print '\n**Job started at ',time.strftime('%c'),'\n'" > job_break_cycles.out 2>&1

python -c "from fba_Pf import break_pf_cycles;break_pf_cycles()" >> job_break_cycles.out 2>&1

python -c "import time;print '\n**Job ended at ',time.strftime('%c'),'\n'" >> job_break_cycles.out 2>&1

