mutants_auxotrophy = {}
mutants_auxotrophy['alaA_alaC_avtA'] = [['EX_LalaDgluMdapDala(e)'], ['EX_alaala(e)'], ['EX_ala_L(e)'], ['EX_LalaLglu(e)'], ['EX_LalaDgluMdap(e)'], ['EX_LalaDglu(e)'], ['EX_ala_D(e)']]
mutants_auxotrophy['argH'] = [['EX_arg_L(e)']]
mutants_auxotrophy['asnA_asnB'] = [['EX_asn_L(e)']]
mutants_auxotrophy['aspC'] = [['EX_asn_L(e)'], ['EX_asp_L(e)']]
mutants_auxotrophy['cysC'] = [['EX_gthrd(e)'], ['EX_cgly(e)'], ['EX_cys_D(e)'], ['EX_cys_L(e)']]
mutants_auxotrophy['glnA'] = [['EX_gln_L(e)']]
mutants_auxotrophy['gltBD_gdhA'] = [['EX_LalaDgluMdapDala(e)'], ['EX_LalaDgluMdap(e)'], ['EX_arg_L(e)'], ['EX_LalaLglu(e)'], ['EX_gthrd(e)'], ['EX_ptrc(e)'], ['EX_alaala(e)'], ['EX_LalaDglu(e)'], ['EX_agm(e)'], ['EX_orn(e)'], ['EX_gln_L(e)'], ['EX_ala_L(e)'], ['EX_asn_L(e)'], ['EX_asp_L(e)'], ['EX_glu_L(e)'], ['EX_4abut(e)'], ['EX_ala_D(e)']]
mutants_auxotrophy['glyA_ltaE'] = [['EX_progly(e)'], ['EX_gly(e)'], ['EX_cgly(e)'], ['EX_gthrd(e)']]
mutants_auxotrophy['hisB'] = [['EX_his_L(e)']]
mutants_auxotrophy['hisC'] = [['EX_his_L(e)']]
mutants_auxotrophy['hisD'] = [['EX_his_L(e)']]
mutants_auxotrophy['hisI'] = [['EX_his_L(e)']]
mutants_auxotrophy['ilvE'] = [['EX_ile_L(e)']]
mutants_auxotrophy['ilvE_avtA'] = [['EX_val_L(e)']]
mutants_auxotrophy['leuB'] = [['EX_leu_L(e)']]
mutants_auxotrophy['leuC'] = [['EX_leu_L(e)']]
mutants_auxotrophy['leuD'] = [['EX_leu_L(e)']]
mutants_auxotrophy['lysA'] = [['EX_frulys(e)'], ['EX_psclys(e)'], ['EX_lys_L(e)']]
mutants_auxotrophy['metC_malY'] = [['EX_met_L(e)'], ['EX_metsox_R_L(e)'], ['EX_metsox_S_L(e)']]
mutants_auxotrophy['proC'] = [['EX_progly(e)'], ['EX_pro_L(e)']]
mutants_auxotrophy['serB_glyA'] = [['EX_pser_L(e)'], ['EX_ser_L(e)'], ['EX_g3ps(e)'], ['EX_ser_D(e)']]
mutants_auxotrophy['thrC'] = [['EX_thr_L(e)'], ['EX_thrp(e)']]
mutants_auxotrophy['trpA'] = [['EX_trp_L(e)']]
mutants_auxotrophy['trpB'] = [['EX_trp_L(e)']]
mutants_auxotrophy['tyrA'] = [['EX_tyrp(e)'], ['EX_tyr_L(e)']]
mutants_auxotrophy['tyrB_ilvE_aspC'] = [['EX_phe_L(e)']]

mutants_exitflags = {}
mutants_exitflags['alaA_alaC_avtA'] = 'infeasible_opt_problem'
mutants_exitflags['argH'] = 'infeasible_opt_problem'
mutants_exitflags['asnA_asnB'] = 'infeasible_opt_problem'
mutants_exitflags['aspC'] = 'infeasible_opt_problem'
mutants_exitflags['cysC'] = 'obj_value_greater_than_max_soln_size'
mutants_exitflags['glnA'] = 'infeasible_opt_problem'
mutants_exitflags['gltBD_gdhA'] = 'infeasible_opt_problem'
mutants_exitflags['glyA_ltaE'] = 'infeasible_opt_problem'
mutants_exitflags['hisB'] = 'infeasible_opt_problem'
mutants_exitflags['hisC'] = 'infeasible_opt_problem'
mutants_exitflags['hisD'] = 'infeasible_opt_problem'
mutants_exitflags['hisI'] = 'infeasible_opt_problem'
mutants_exitflags['ilvE'] = 'infeasible_opt_problem'
mutants_exitflags['ilvE_avtA'] = 'infeasible_opt_problem'
mutants_exitflags['leuB'] = 'infeasible_opt_problem'
mutants_exitflags['leuC'] = 'infeasible_opt_problem'
mutants_exitflags['leuD'] = 'infeasible_opt_problem'
mutants_exitflags['lysA'] = 'infeasible_opt_problem'
mutants_exitflags['metC_malY'] = 'infeasible_opt_problem'
mutants_exitflags['proC'] = 'infeasible_opt_problem'
mutants_exitflags['serB_glyA'] = 'infeasible_opt_problem'
mutants_exitflags['thrC'] = 'infeasible_opt_problem'
mutants_exitflags['trpA'] = 'infeasible_opt_problem'
mutants_exitflags['trpB'] = 'infeasible_opt_problem'
mutants_exitflags['tyrA'] = 'infeasible_opt_problem'
mutants_exitflags['tyrB_ilvE_aspC'] = 'infeasible_opt_problem'
